"""Optional local super-resolution lane for Adobe Stock U-button assets.

This does not spend Midjourney Fast hours. It only runs when a local Real-ESRGAN
compatible CLI is configured through OPENCLAW_REALESRGAN_EXE and the caller
explicitly passes --execute. The final production file is generated by:

1. copy selected U-button asset into Pending_Upscale;
2. run 4x super-resolution into a temporary folder;
3. downsample to a conservative 4000x2667 JPEG to compress hallucinated detail;
4. leave the result for the normal OpenClaw visual QA gates.
"""

from __future__ import annotations

import argparse
import csv
import os
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from PIL import Image, ImageEnhance, ImageFilter

from adobe_stock_quality_policy import edge_detail_score


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATABASE = PROJECT_ROOT / "Database"
REVIEW = PROJECT_ROOT / "Review_Packets"
PROGRESS_LOG = PROJECT_ROOT / "PROGRESS_LOG.md"
SOURCE = DATABASE / "Adobe_Stock_Daily_U_Candidates.csv"
OUT = DATABASE / "Adobe_Stock_Superres_Candidates.csv"
REPORT = REVIEW / "Adobe_Stock_Superres_Pipeline_latest.md"
PENDING_DIR = PROJECT_ROOT / "adobe_stock_factory" / "Pending_Upscale"
TEMP_DIR = PROJECT_ROOT / "adobe_stock_factory" / "_superres_temp"
FINAL_DIR = PROJECT_ROOT / "adobe_stock_factory" / "superres_ready"
ET = ZoneInfo("America/New_York")

FINAL_WIDTH = 4000
FINAL_HEIGHT = 2667
FIELDS = [
    "Asset_ID",
    "Family",
    "Title",
    "Keywords",
    "Source_Path",
    "Pending_Path",
    "Superres_Path",
    "Final_Path",
    "Width",
    "Height",
    "Pixels",
    "File_Bytes",
    "Edge_Detail_Score",
    "Status",
    "Issues",
]


def now() -> datetime:
    return datetime.now(ET)


def now_text() -> str:
    return now().strftime("%Y-%m-%d %H:%M:%S %Z")


def clean(value: object) -> str:
    return " ".join(str(value or "").replace("\r", " ").replace("\n", " ").split()).strip()


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in FIELDS})


def resolve(path_text: str) -> Path:
    path = Path(path_text)
    if not path.is_absolute():
        path = PROJECT_ROOT / path
    return path


def safe_stem(value: str) -> str:
    out = "".join(ch.lower() if ch.isalnum() else "_" for ch in value)
    while "__" in out:
        out = out.replace("__", "_")
    return out.strip("_") or "adobe_asset"


def in_cool_window(force: bool) -> bool:
    if force:
        return True
    hour = now().hour
    return 2 <= hour < 8


def downsample(superres_path: Path, final_path: Path) -> tuple[int, int, int, float]:
    with Image.open(superres_path) as image:
        image = image.convert("RGB")
        image = image.resize((FINAL_WIDTH, FINAL_HEIGHT), Image.Resampling.LANCZOS)
        image = image.filter(ImageFilter.UnsharpMask(radius=0.8, percent=45, threshold=3))
        image = ImageEnhance.Contrast(image).enhance(1.02)
        final_path.parent.mkdir(parents=True, exist_ok=True)
        image.save(final_path, "JPEG", quality=94, optimize=True, progressive=True)
    return FINAL_WIDTH, FINAL_HEIGHT, final_path.stat().st_size, edge_detail_score(final_path)


def build_row(source_row: dict[str, str], exe: Path | None, execute: bool, force: bool) -> dict[str, str]:
    asset_id = clean(source_row.get("Asset_ID"))
    source_path = resolve(clean(source_row.get("Source_Path")))
    stem = safe_stem(asset_id)
    pending_path = PENDING_DIR / f"{stem}{source_path.suffix.lower() or '.png'}"
    superres_path = TEMP_DIR / f"{stem}_x4.jpg"
    final_path = FINAL_DIR / f"{stem}_4000x2667.jpg"
    row = {
        "Asset_ID": asset_id,
        "Family": clean(source_row.get("Family")),
        "Title": clean(source_row.get("Title")),
        "Keywords": clean(source_row.get("Keywords")),
        "Source_Path": str(source_path.relative_to(PROJECT_ROOT)) if source_path.exists() else clean(source_row.get("Source_Path")),
        "Pending_Path": str(pending_path.relative_to(PROJECT_ROOT)),
        "Superres_Path": str(superres_path.relative_to(PROJECT_ROOT)),
        "Final_Path": str(final_path.relative_to(PROJECT_ROOT)),
    }
    if not source_path.exists():
        return {**row, "Status": "HOLD_SOURCE_MISSING", "Issues": "source U-button file missing"}
    PENDING_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_path, pending_path)
    if not exe:
        return {**row, "Status": "READY_PENDING_REALESRGAN_EXE", "Issues": "set OPENCLAW_REALESRGAN_EXE to enable local 4x super-resolution"}
    if not in_cool_window(force):
        return {**row, "Status": "HOLD_THERMAL_WINDOW_WAIT_FOR_02_08_ET", "Issues": "super-resolution is heavy; wait for cool window or --force"}
    if not execute:
        return {**row, "Status": "DRY_RUN_READY_FOR_SUPERRES", "Issues": "pass --execute to run local super-resolution"}
    TEMP_DIR.mkdir(parents=True, exist_ok=True)
    command = [str(exe), "-i", str(pending_path), "-o", str(superres_path), "-n", os.getenv("OPENCLAW_REALESRGAN_MODEL", "realesrgan-x4plus"), "-s", "4", "-f", "jpg"]
    try:
        completed = subprocess.run(command, cwd=PROJECT_ROOT, capture_output=True, text=True, timeout=900)
    except Exception as exc:
        return {**row, "Status": f"HOLD_SUPERRES_ERROR:{type(exc).__name__}", "Issues": repr(exc)[:220]}
    if completed.returncode != 0 or not superres_path.exists():
        return {
            **row,
            "Status": f"HOLD_SUPERRES_RC_{completed.returncode}",
            "Issues": (completed.stderr or completed.stdout or "superres output missing")[:220],
        }
    width, height, file_bytes, edge_score = downsample(superres_path, final_path)
    return {
        **row,
        "Width": str(width),
        "Height": str(height),
        "Pixels": str(width * height),
        "File_Bytes": str(file_bytes),
        "Edge_Detail_Score": f"{edge_score:.2f}",
        "Status": "READY_FOR_REX_VISUAL_QA_SUPERRES_NOT_SUBMITTED",
        "Issues": "",
    }


def write_report(rows: list[dict[str, str]], exe: Path | None) -> None:
    status_counts: dict[str, int] = {}
    for row in rows:
        status_counts[row.get("Status", "")] = status_counts.get(row.get("Status", ""), 0) + 1
    lines = [
        "# Adobe Stock Local Super-Resolution Pipeline",
        "",
        f"Generated: {now_text()}",
        f"Real-ESRGAN executable: `{exe or 'NOT CONFIGURED'}`",
        f"Rows: {len(rows)}",
        f"Status counts: {status_counts}",
        "",
        "## Policy",
        "",
        "- No Midjourney Fast hours.",
        "- Only selected U-button files enter this lane; grids stay as review evidence.",
        "- Heavy super-resolution is cool-window only unless explicitly forced.",
        "- Final 4000x2667 downsample still requires visual QA before Adobe upload.",
    ]
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def append_progress(rows: list[dict[str, str]]) -> None:
    with PROGRESS_LOG.open("a", encoding="utf-8") as handle:
        handle.write(
            f"\n- {now_text()}: Adobe Stock local super-resolution lane checked; "
            f"rows={len(rows)}; no upload/spend.\n"
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=12)
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    exe_text = os.getenv("OPENCLAW_REALESRGAN_EXE", "").strip()
    exe = Path(exe_text) if exe_text else None
    if exe and not exe.exists():
        exe = None
    rows = []
    for source_row in read_csv(SOURCE)[: max(1, args.limit)]:
        rows.append(build_row(source_row, exe, args.execute, args.force))
    write_csv(OUT, rows)
    write_report(rows, exe)
    append_progress(rows)
    print(f"[ADOBE-SUPERRES] rows={len(rows)} exe={'yes' if exe else 'missing'} csv={OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
